### PR TITLE
handle inline issue

### PR DESCRIPTION
**Pull request by netanelgonen**
this small change solve any compilation issue that we may have with inline.
the current trick is not working

### CODE REVIEW

**Comment by kjbracey-arm** [comment]
More explanation required.

The code as written assumes C99 or later, or C++03 or later, and is perfectly valid for standard compilers.

I'm guessing the problem you're having is you're probably including a header file using that, and not including the C file. For example, including ns_list.h, but not including ns_list.c in the build.

With some toolchains, that will fail - it's not a valid thing to do. ns_list.c must be included to provide the real non-inline definition.

**Comment by kjbracey-arm** [comment]
Note also the current code is not GCC-specific. Your new code uses GCC extensions. The code is supposed to be portable (to any C99 or later compiler).

**Comment by netanelgonen** [comment]
Hi @kjbracey-arm ,

this issue is as following,
in compiling our project with the following flags (taken from mbed compile flags):
 ASM flags:
 "-c"
 "-Wall"
 "-Wextra"
 "-Wno-unused-parameter"
 "-Wno-missing-field-initializers"
 "-fmessage-length=0"
 "-fno-exceptions"
 "-fno-builtin"
 "-ffunction-sections"
 "-fdata-sections"
 "-funsigned-char"
 "-MMD"
 "-fno-delete-null-pointer-checks"
 "-fomit-frame-pointer"
 "-x"
 "-assembler-with-cpp"
 
C Flags:
"-c"
"-Wall"
"-Wextra"
"-Wno-unused-parameter"
"-Wno-missing-field-initializers"
"-fmessage-length=0"
"-fno-exceptions"
"-fno-builtin"
"-ffunction-sections"
"-fdata-sections"
"-funsigned-char"
"-MMD"
"-fno-delete-null-pointer-checks"
"-fomit-frame-pointer"
"-std=gnu99"

 CXX flags:
 "-c"
 "-Wall"
 "-Wextra"
 "-Wno-unused-parameter"
 "-Wno-missing-field-initializers"
 "-fmessage-length=0"
 "-fno-exceptions"
 "-fno-builtin"
 "-ffunction-sections"
 "-fdata-sections"
 "-funsigned-char"
 "-MMD"
 "-fno-delete-null-pointer-checks"
 "-fomit-frame-pointer"
 "-std=gnu++98"
 "-fno-rtti"
 "-Wvla"
 
ld flags:
"-Wl,--gc-sections"

while compiling on O1 everything goes fine.
but when I'm trying to compile with O0 (for debug) im getting the following error:
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `cmd_init':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:259: undefined reference to `ns_list_init_'
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:260: undefined reference to `ns_list_init_'
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:261: undefined reference to `ns_list_init_'
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:262: undefined reference to `ns_list_init_'
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:263: undefined reference to `ns_list_init_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `cmd_pop':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:431: undefined reference to `ns_list_get_next_'
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:438: undefined reference to `ns_list_remove_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `cmd_push':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:507: undefined reference to `ns_list_add_to_end_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `cmd_find_n':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:575: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `cmd_find':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:621: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `cmd_add':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:644: undefined reference to `ns_list_add_to_end_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `goto_end_of_history':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1008: undefined reference to `ns_list_get_last_'
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1010: undefined reference to `ns_list_count_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `cmd_replace_alias':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1203: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `cmd_replace_variables':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1228: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `cmd_history_item_delete':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1235: undefined reference to `ns_list_remove_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `cmd_history_find':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1244: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `cmd_history_clean_overflow':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1257: undefined reference to `ns_list_get_last_'
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1256: undefined reference to `ns_list_count_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `cmd_history_clean':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1266: undefined reference to `ns_list_get_last_'
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1264: undefined reference to `ns_list_count_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `cmd_history_save':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1284: undefined reference to `ns_list_add_to_start_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `alias_find':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1346: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `alias_find_n':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1364: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `variable_find':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1383: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `variable_find_n':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1399: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `cmd_alias_print_all':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1412: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj):/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1421: more undefined references to `ns_list_get_next_' follow
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `cmd_alias_add':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1445: undefined reference to `ns_list_add_to_end_'
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1452: undefined reference to `ns_list_remove_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `cmd_variable_add':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1483: undefined reference to `ns_list_add_to_end_'
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1490: undefined reference to `ns_list_remove_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `help_command':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1623: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(ns_cmdline.c.obj): In function `history_command':
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1644: undefined reference to `ns_list_count_'
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1646: undefined reference to `ns_list_get_last_'
/home/gonen/work/proj/mbed-client-testapp/mbed-client-cli/source/ns_cmdline.c:1646: undefined reference to `ns_list_get_previous_'
Debug/libmbedClientTestapp.a(sn_coap_protocol.c.obj): In function `sn_coap_protocol_destroy':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:119: undefined reference to `ns_list_remove_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:110: undefined reference to `ns_list_get_next_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:134: undefined reference to `ns_list_remove_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:124: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(sn_coap_protocol.c.obj): In function `sn_coap_protocol_init':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:178: undefined reference to `ns_list_init_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:195: undefined reference to `ns_list_init_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:196: undefined reference to `ns_list_init_'
Debug/libmbedClientTestapp.a(sn_coap_protocol.c.obj): In function `sn_coap_protocol_clear_retransmission_buffer':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:302: undefined reference to `ns_list_get_next_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:303: undefined reference to `ns_list_remove_'
Debug/libmbedClientTestapp.a(sn_coap_protocol.c.obj): In function `sn_coap_protocol_build':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:478: undefined reference to `ns_list_add_to_end_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:503: undefined reference to `ns_list_add_to_end_'
Debug/libmbedClientTestapp.a(sn_coap_protocol.c.obj): In function `sn_coap_protocol_parse':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:638: undefined reference to `ns_list_get_next_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:647: undefined reference to `ns_list_remove_'
Debug/libmbedClientTestapp.a(sn_coap_protocol.c.obj): In function `sn_coap_protocol_exec':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:720: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(sn_coap_protocol.c.obj): In function `sn_coap_protocol_linked_list_send_msg_store':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:841: undefined reference to `ns_list_add_to_end_'
Debug/libmbedClientTestapp.a(sn_coap_protocol.c.obj): In function `sn_coap_protocol_linked_list_send_msg_search':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:863: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(sn_coap_protocol.c.obj): In function `sn_coap_protocol_linked_list_send_msg_remove':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:910: undefined reference to `ns_list_remove_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:896: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(sn_coap_protocol.c.obj): In function `sn_coap_protocol_linked_list_blockwise_msg_remove':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:1103: undefined reference to `ns_list_remove_'
Debug/libmbedClientTestapp.a(sn_coap_protocol.c.obj): In function `sn_coap_protocol_linked_list_blockwise_payload_store':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:1182: undefined reference to `ns_list_add_to_end_'
Debug/libmbedClientTestapp.a(sn_coap_protocol.c.obj): In function `sn_coap_protocol_linked_list_blockwise_payload_search':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:1200: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(sn_coap_protocol.c.obj): In function `sn_coap_protocol_linked_list_blockwise_payload_remove':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:1246: undefined reference to `ns_list_remove_'
Debug/libmbedClientTestapp.a(sn_coap_protocol.c.obj): In function `sn_coap_protocol_linked_list_blockwise_payloads_get_len':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:1277: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(sn_coap_protocol.c.obj): In function `sn_coap_protocol_linked_list_blockwise_remove_old_data':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:1300: undefined reference to `ns_list_get_next_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:1318: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(sn_coap_protocol.c.obj): In function `sn_coap_count_linked_list_size':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:1410: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(sn_coap_protocol.c.obj): In function `sn_coap_protocol_block_remove':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:1429: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(sn_coap_protocol.c.obj):/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:1483: more undefined references to `ns_list_get_next_' follow
Debug/libmbedClientTestapp.a(sn_coap_protocol.c.obj): In function `sn_coap_handle_blockwise_message':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:1722: undefined reference to `ns_list_remove_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-coap/source/sn_coap_protocol.c:1805: undefined reference to `ns_list_add_to_end_'
Debug/libmbedClientTestapp.a(sn_grs.c.obj): In function `sn_grs_destroy':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-client/mbed-client-c/source/sn_grs.c:64: undefined reference to `ns_list_get_next_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-client/mbed-client-c/source/sn_grs.c:65: undefined reference to `ns_list_remove_'
Debug/libmbedClientTestapp.a(sn_grs.c.obj): In function `sn_grs_get_next_resource':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-client/mbed-client-c/source/sn_grs.c:246: undefined reference to `ns_list_get_next_'
Debug/libmbedClientTestapp.a(sn_grs.c.obj): In function `sn_grs_put_resource':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-client/mbed-client-c/source/sn_grs.c:507: undefined reference to `ns_list_add_to_start_'
Debug/libmbedClientTestapp.a(sn_grs.c.obj): In function `sn_grs_pop_resource':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-client/mbed-client-c/source/sn_grs.c:531: undefined reference to `ns_list_remove_'
Debug/libmbedClientTestapp.a(sn_grs.c.obj): In function `sn_grs_search_resource':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-client/mbed-client-c/source/sn_grs.c:888: undefined reference to `ns_list_get_next_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/mbed-client/mbed-client-c/source/sn_grs.c:903: undefined reference to `ns_list_get_next_'
Debug/libmbedCloudClient.a(event.c.obj): In function `event_tasklet_handler_get':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/event.c:53: undefined reference to `ns_list_get_next_'
Debug/libmbedCloudClient.a(event.c.obj): In function `eventOS_event_handler_create':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/event.c:85: undefined reference to `ns_list_get_next_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/event.c:106: undefined reference to `ns_list_add_to_end_'
Debug/libmbedCloudClient.a(event.c.obj): In function `eventOS_event_cancel_critical':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/event.c:145: undefined reference to `ns_list_remove_'
Debug/libmbedCloudClient.a(event.c.obj): In function `event_core_get':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/event.c:168: undefined reference to `ns_list_remove_'
Debug/libmbedCloudClient.a(event.c.obj): In function `event_core_free_push':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/event.c:187: undefined reference to `ns_list_add_to_start_'
Debug/libmbedCloudClient.a(event.c.obj): In function `event_core_read':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/event.c:211: undefined reference to `ns_list_remove_'
Debug/libmbedCloudClient.a(event.c.obj): In function `event_core_write':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/event.c:224: undefined reference to `ns_list_add_before_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/event.c:221: undefined reference to `ns_list_get_next_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/event.c:230: undefined reference to `ns_list_add_to_end_'
Debug/libmbedCloudClient.a(event.c.obj): In function `eventOS_event_find_by_id_critical':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/event.c:242: undefined reference to `ns_list_get_next_'
Debug/libmbedCloudClient.a(event.c.obj): In function `eventOS_scheduler_init':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/event.c:261: undefined reference to `ns_list_init_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/event.c:262: undefined reference to `ns_list_init_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/event.c:263: undefined reference to `ns_list_init_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/event.c:268: undefined reference to `ns_list_add_to_start_'
Debug/libmbedCloudClient.a(system_timer.c.obj): In function `timer_sys_init':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/system_timer.c:94: undefined reference to `ns_list_add_to_start_'
Debug/libmbedCloudClient.a(system_timer.c.obj): In function `timer_struct_get':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/system_timer.c:138: undefined reference to `ns_list_remove_'
Debug/libmbedCloudClient.a(system_timer.c.obj): In function `timer_sys_event_free':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/system_timer.c:152: undefined reference to `ns_list_add_to_start_'
Debug/libmbedCloudClient.a(system_timer.c.obj): In function `timer_sys_event_cancel_critical':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/system_timer.c:173: undefined reference to `ns_list_remove_'
Debug/libmbedCloudClient.a(system_timer.c.obj): In function `timer_sys_add':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/system_timer.c:197: undefined reference to `ns_list_add_before_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/system_timer.c:195: undefined reference to `ns_list_get_next_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/system_timer.c:203: undefined reference to `ns_list_add_to_end_'
Debug/libmbedCloudClient.a(system_timer.c.obj): In function `eventOS_event_timer_cancel':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/system_timer.c:310: undefined reference to `ns_list_get_next_'
Debug/libmbedCloudClient.a(system_timer.c.obj): In function `system_timer_tick_update':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/system_timer.c:361: undefined reference to `ns_list_remove_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/sal-stack-nanostack-eventloop/source/system_timer.c:358: undefined reference to `ns_list_get_next_'
Debug/libmbedCloudClient.a(nsdynmemLIB.c.obj): In function `ns_dyn_mem_init':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c:95: undefined reference to `ns_list_init_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c:96: undefined reference to `ns_list_add_to_start_'
Debug/libmbedCloudClient.a(nsdynmemLIB.c.obj): In function `ns_dyn_mem_internal_alloc':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c:184: undefined reference to `ns_list_get_last_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c:187: undefined reference to `ns_list_get_next_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c:187: undefined reference to `ns_list_get_previous_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c:217: undefined reference to `ns_list_get_previous_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c:218: undefined reference to `ns_list_remove_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c:220: undefined reference to `ns_list_add_after_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c:222: undefined reference to `ns_list_add_to_start_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c:235: undefined reference to `ns_list_remove_'
Debug/libmbedCloudClient.a(nsdynmemLIB.c.obj): In function `ns_free_and_merge_with_adjacent_blocks':
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c:329: undefined reference to `ns_list_get_next_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c:330: undefined reference to `ns_list_remove_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c:343: undefined reference to `ns_list_get_next_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c:351: undefined reference to `ns_list_add_before_'
/home/gonen/work/proj/mbed-client-testapp/mbed-cloud-client/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c:353: undefined reference to `ns_list_add_to_end_'
collect2: error: ld returned 1 exit status
make[3]: *** [Debug/mbedClientTestapp.elf] Error 1
make[2]: *** [CMakeFiles/mbedClientTestapp.elf.dir/all] Error 2
make[1]: *** [CMakeFiles/mbedClientTestapp.elf.dir/rule] Error 2
make: *** [mbedClientTestapp.elf] Error 2

do you have any good solution?

**Comment by kjbracey-arm** [comment]
Yes, include ns_list.c in the build.

Just like any normal code, if you don't include the C file, the H file won't generally work.

You happen to get away with it if the compiler happens to inline everything, but the compiler isn't guaranteed to. C99 requires there to be external definitions available, which means the C file must be included - you can't leave it out.

**Comment by kjbracey-arm** [comment]
Note that these functions are deliberately extern inline rather than static inline, to allow for the possibility that they're not inlined if the compiler decides they're too complicated, possibly on the basis of "-Ospace".

Forcing always inlining would potentially end up forcing the image size up, when we care about image size more than speed.

(I'm not actually sure which compilers do what with which compilation profile options, but writing the code this way gives them flexibility).

**Comment by netanelgonen** [comment]
thanks this solved the issue,
can i use this in both O3 and O0?

**Comment by kjbracey-arm** [comment]
If ns_list.c is present, it will work on any compiler at any optimisation level.

If the compiler does inline all calls (eg at -O3 and no-one takes the address of the functions), then the external definitions from ns_list.c just won't be pulled in to the image.

The "linker behaviour varies depending on optimisation level" is an unfortunate compiler feature. Would be nice if there were dummy references added to object files to generate the same unresolved symbol errors even when inlining, to make sure people were remembering the C rules. I did that when implementing inline in a compiler once.

Only other thing you now need to be aware of is just making sure you don't manage to put multiple copies of ns_list.c into a build. If you did, that probably would only throw up duplicate definition errors when not inlining (-O0).

**Comment by kjbracey-arm** [comment]
BTW, the only other "extern inline definitions" file currently in libservice common_functions.c, so that also needs to be in the build if you're using inline functions like `common_read_32_bit`.

But presumably you are already including that C file as it has some non-inline functions like `bitcopy`.

ns_list.c is unusual in only containing extern inline functions, so builds can sometimes manage without it.

**Comment by netanelgonen** [comment]
the issue was solved, closing PR

**Pull request closed without merging**
